[tool.poetry]
name = "instaclone"
version = "0.1.0"
description = ""
authors = ["avelyno <kou2295@calu.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
django = "^3.0.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
